apiVersion: v1
kind: Service
metadata:
  name: commafeed-service
  namespace: commafeed
spec:
  selector:
    app: commafeed
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
