server:
  persistentVolume:
    enabled: true
    size: 8Gi
    storageClass: longhorn-static
  global:
    scrape_interval: 30s

alertmanager:
  persistence:
    enabled: true
    storageClass: longhorn-static

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
