repositories:
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts

releases:
  - name: tailscale-operator
    namespace: tailscale
    chart: tailscale/tailscale-operator
    createNamespace: true
    wait: true
    values:
      - values.yaml
