oauth:
  clientId: ${TAILSCALE_OAUTH_CLIENT_ID}
  clientSecret: ${TAILSCALE_OAUTH_CLIENT_SECRET}

operatorConfig:
  hostname: tailscale-operator
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
