repositories:
  - name: longhorn
    url: https://charts.longhorn.io

releases:
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    createNamespace: false  # namespace.yaml has required pod-security label
    wait: true
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "namespace.yaml"]
    values:
      - values.yaml
