---
- import_playbook: playbooks/install_tailscale.yml
  tags: [tailscale, never]
  vars:
    target_hosts: proxmox-ssh

- import_playbook: playbooks/disable_power_off.yml
  tags: [proxmox, never]
  vars:
    target_hosts: proxmox-tailscale

- import_playbook: playbooks/disable_password_auth.yml
  tags: [proxmox, never]
  vars:
    target_hosts: proxmox-tailscale

- import_playbook: playbooks/update_apt.yml
  tags: [proxmox, never]
  vars:
    target_hosts: proxmox-tailscale

- import_playbook: playbooks/install_vault.yml
  tags: [vault]
  vars:
    target_hosts: vault-tailscale
    s3_bucket_name: "{{ lookup('env', 'VAULT_S3_BUCKET_NAME') }}"
